#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'TTGTagCollectionView_Example' do
  pod 'TTGTagCollectionView', :path => '../'
  pod 'Masonry'
  pod 'SVPullToRefresh'

  target 'TTGTagCollectionView_Tests' do
    inherit! :search_paths
  end
end
